# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71d614c8980352c59da9a3bbf4d6e0a93d5f3ab1cd0334c1c73adc153aed7545c752e7bd137f1b5bb1dc8c0eb31cc25d9da680829a494db8210b0bed063efd05

test:
  secret_key_base: 066c642dc613abcaa9cdeffb0dfb7e3d8bab7033740d1ba0e519f154c550a573a29a38d035c5a468861b167edbd34c2c4cf2be5895b34d9a7a8d9daf68dc259f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
